# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171117_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='bg_image',
            field=models.ImageField(default='image/default', upload_to='banner/%Y/%m', verbose_name='背景图'),
        ),
    ]
