# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170909_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResourse',
            new_name='CourseResource',
        ),
    ]
